# Generated by Django 2.0 on 2017-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Duplex', 'Duplex'), ('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('BQ', 'BQ')], max_length=20)),
                ('bed_no', models.IntegerField(verbose_name='bedroom')),
                ('sitting_no', models.IntegerField(verbose_name='sitting_room')),
                ('toilet_no', models.IntegerField(verbose_name='toilet')),
                ('house_img', models.ImageField(upload_to='static')),
                ('sitting_room_img', models.ImageField(upload_to='static')),
                ('bedroom_img', models.ImageField(upload_to='static')),
                ('bathroom_img', models.ImageField(upload_to='static')),
            ],
        ),
    ]
