# Generated by Django 2.0 on 2017-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_properties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='bathroom_img',
            field=models.ImageField(upload_to='properties/static/properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='bedroom_img',
            field=models.ImageField(upload_to='properties/static/properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='house_img',
            field=models.ImageField(upload_to='properties/static/properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sitting_room_img',
            field=models.ImageField(upload_to='properties/static/properties'),
        ),
    ]
